/**
 * MONTEX ERP Premium - Tipos de Ações Globais
 *
 * Enumeração centralizada de todos os tipos de ações
 * utilizadas nos reducers da aplicação.
 */

export const ACTIONS = {
  // Obras
  SET_OBRA_ATUAL: 'SET_OBRA_ATUAL',
  UPDATE_OBRA: 'UPDATE_OBRA',
  ADD_OBRA: 'ADD_OBRA',
  UPDATE_PROGRESSO_OBRA: 'UPDATE_PROGRESSO_OBRA',

  // Orçamentos
  UPDATE_ORCAMENTO: 'UPDATE_ORCAMENTO',
  ADD_ORCAMENTO: 'ADD_ORCAMENTO',
  APROVAR_ORCAMENTO: 'APROVAR_ORCAMENTO',

  // Estoque
  UPDATE_ESTOQUE: 'UPDATE_ESTOQUE',
  CONSUMIR_ESTOQUE: 'CONSUMIR_ESTOQUE',
  ADICIONAR_ESTOQUE: 'ADICIONAR_ESTOQUE',
  RESERVAR_ESTOQUE: 'RESERVAR_ESTOQUE',

  // Peças/Produção
  UPDATE_PECA: 'UPDATE_PECA',
  MOVER_PECA_ETAPA: 'MOVER_PECA_ETAPA',
  UPDATE_STATUS_CORTE: 'UPDATE_STATUS_CORTE',
  ADD_PECAS: 'ADD_PECAS',

  // Expedição
  ADD_EXPEDICAO: 'ADD_EXPEDICAO',
  UPDATE_EXPEDICAO: 'UPDATE_EXPEDICAO',

  // Compras
  ADD_COMPRA: 'ADD_COMPRA',
  UPDATE_COMPRA: 'UPDATE_COMPRA',
  RECEBER_COMPRA: 'RECEBER_COMPRA',

  // Medições
  ADD_MEDICAO: 'ADD_MEDICAO',
  UPDATE_CONFIG_MEDICAO: 'UPDATE_CONFIG_MEDICAO',

  // Lançamentos / Despesas
  ADD_LANCAMENTO: 'ADD_LANCAMENTO',
  UPDATE_LANCAMENTO: 'UPDATE_LANCAMENTO',

  // Funcionários e Equipes
  UPDATE_FUNCIONARIO: 'UPDATE_FUNCIONARIO',
  UPDATE_EQUIPE: 'UPDATE_EQUIPE',
  ALOCAR_EQUIPE: 'ALOCAR_EQUIPE',

  // Máquinas
  UPDATE_MAQUINA: 'UPDATE_MAQUINA',

  // Listas
  IMPORTAR_LISTA: 'IMPORTAR_LISTA',

  // Materiais (Controle de Estoque em Peso KG)
  IMPORTAR_MATERIAIS: 'IMPORTAR_MATERIAIS',
  REGISTRAR_ENTREGA_MATERIAL: 'REGISTRAR_ENTREGA_MATERIAL',
  UPDATE_MATERIAL: 'UPDATE_MATERIAL',

  // Inicialização Supabase
  INIT_FROM_SUPABASE: 'INIT_FROM_SUPABASE',

  // UI
  SET_FILTROS: 'SET_FILTROS',
  SET_LOADING: 'SET_LOADING',
  ADD_NOTIFICACAO: 'ADD_NOTIFICACAO',
  REMOVE_NOTIFICACAO: 'REMOVE_NOTIFICACAO'
};
